language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install PyMySQL . pytest mock codecov pexpect behave
  - pip install git+https://github.com/hayd/pep8radius.git

script:
  - set -e
  - coverage run --source mycli -m py.test
  - cd test
  - behave
  - cd ..
  # check for pep8 errors, only looking at branch vs master. If there are errors, show diff and return an error code.
  - pep8radius master --docformatter --error-status || ( pep8radius master --docformatter --diff; false )
  - set +e

after_success:
  - coverage combine
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
