environment:
  PYTEST_PASSWORD: Password12!

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

services:
  - mysql

build: off

before_test:
  - "%PYTHON%\\python.exe -m pip install -r requirements-dev.txt"
  - "%PYTHON%\\python.exe -m pip install -e ."
test_script:
  - "%PYTHON%\\python.exe setup.py test lint"
